name: co
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.6.0
  navigation_dot_bar: ^0.1.3
  flutter_spinkit: ^4.1.1
  splashscreen: ^1.2.0
  shared_preferences: ^0.5.3+4
  flutter_launcher_icons: ^0.7.4
  flappy_search_bar: ^1.7.2









dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "images/app_logo/logo.png"
  image_path_ios: "images/app_logo/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - images/app_logo/logo.png
   - images/app_logo/splash_logo.png
   
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Gilroy-Light
        fonts:
          - asset: fonts/Gilroy-Light.otf

      - family: Gilroy-ExtraBold
        fonts:
          - asset: fonts/Gilroy-ExtraBold.otf

      - family: Inter-Black
        fonts:
          - asset: fonts/Inter-Black.ttf

      - family: Inter-Bold
        fonts:
          - asset: fonts/Inter-Bold.ttf

      - family: Inter-ExtraBold
        fonts:
          - asset: fonts/Inter-ExtraBold.ttf

      - family: Inter-ExtraLight
        fonts:
          - asset: fonts/Inter-ExtraLight-BETA.ttf

      - family: Inter-Light
        fonts:
          - asset: fonts/Inter-Light-BETA.ttf

      - family: Inter-Medium
        fonts:
          - asset: fonts/Inter-Medium.ttf

      - family: Inter-Regular
        fonts:
          - asset: fonts/Inter-Regular.ttf

      - family: Inter-SemiBold
        fonts:
          - asset: fonts/Inter-SemiBold.ttf

      - family: Inter-Thin-BETA
        fonts:
          - asset: fonts/Inter-Thin-BETA.ttf
      
      - family: Poppins
        fonts:
          - asset: fonts/Poppins-ExtraBold.otf 
      
      - family: RedHat
        fonts:
          - asset: fonts/RedHatText-Bold.otf
      
      - family: Poppins-Thin
        fonts:
          - asset: fonts/Poppins-Thin.otf    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
